// @ts-ignore
import colors from 'tailwindcss/colors'

export const FILIERES_LIST = ['SMI', 'SMPC', 'GLNT'] as const

export const DEPARTEMENT_LIST = [
  'Computer Science',
  'Physics',
  'Mathematics',
] as const

export const FORMAT_LIST = ['A3', 'A4'] as const

export const DURATION_LIST = ['1h', '1.5h', '2h'] as const

export const MODULE_LIST = ['Networks', 'Module 2', 'Module 3'] as const

export const SESSION_LIST = (() => {
  const d = new Date()
  let year = d.getFullYear()
  return [
    `Autumn ${year}/${year - 1}`,
    `Spring ${year}/${year - 1}`,
    `Autumn ${year}/${year + 1}`,
    `Spring ${year}/${year + 1}`,
    `Autumn ${year}/${year + 2}`,
    `Spring ${year}/${year + 2}`,
    `Autumn ${year}/${year + 3}`,
    `Spring ${year}/${year + 3}`,
  ] as const
})()

export const QUESTION_TYPES_LIST = [
  {
    id: 'multiple_choices',
    value: 'Multiple',
  },
  {
    id: 'true_false',
    value: 'True/False',
  },
  {
    id: 'long',
    value: 'Long',
  },
] as const

export const LONG_BAREME_COLORS: Record<string, string> = {
  A: colors.green[500],
  B: colors.blue[500],
  C: colors.yellow[500],
  D: colors.purple[500],
  E: colors.violet[500],
  F: colors.teal[500],
}

export const LATEX_MATH_EXPRESSIONS = [
  '\\frac{a}{b}',
  '\\sqrt{a}',
  '\\sqrt[n]{a}',
  'a^{b}',
  'a_{b}',
  '\\sum_{i=1}^{n}',
  '\\prod_{n=1}^{\\infty}',
  '\\lim_{x \\to \\infty}',
  '\\bigcup_{n=1}^{10}',
  '\\bigcap_{n=1}^{10}',
  '\\log_{a}b',
  '\\int_{a}^{b}',
  '\\infty',
  '\\sin{a}',
  '\\overrightarrow{AB}',
  '\\overline{AB}',
  '\\widehat{AB}',
]

export const LATEX_MATH_SYMBOLS = [
  '\\alpha',
  '\\beta',
  '\\gamma',
  '\\delta',
  '\\epsilon',
  '\\varepsilon',
  '\\zeta',
  '\\eta',
  '\\Gamma',
  '\\Delta',
  '\\Theta',
  '\\theta',
  '\\vartheta',
  '\\iota',
  '\\kappa',
  '\\lambda',
  '\\mu',
  '\\nu',
  '\\xi',
  '\\Lambda',
  '\\Pi',
  'o',
  '\\pi',
  '\\varpi',
  '\\rho',
  '\\varrho',
  '\\sigma',
  '\\varsigma',
  '\\tau',
  '\\Sigma',
  '\\Upsilon',
  '\\Phi',
  '\\upsilon',
  '\\phi',
  '\\varphi',
  '\\chi',
  '\\psi',
  '\\omega',
  '\\Psi',
  '\\Omega',
  '<',
  '>',
  '=',
  '\\leq',
  '\\le',
  '\\geq',
  '\\ge',
  '\\equiv',
  '\\ll',
  '\\gg',
  '\\doteq',
  '\\prec',
  '\\succ',
  '\\sim',
  '\\preceq',
  '\\succeq',
  '\\simeq',
  '\\subset',
  '\\approx',
  '\\subseteq',
  '\\cong',
  '\\sqsubset',
  '\\Join',
  '\\sqsubseteq',
  '\\bowtie',
  '\\in',
  '\\ni',
  '\\owns',
  '\\propto',
  '\\vdash',
  '\\dashv',
  '\\models',
  '\\mid',
  '\\parallel',
  '\\perp',
  '\\smile',
  '\\frown',
  '\\asymp',
  ':',
  '\\notin',
  '\\neq',
  '\\ne',
  '+',
  '-',
  '\\pm',
  '\\mp',
  '\\triangleleft',
  '\\cdot',
  '\\div',
  '\\triangleright',
  '\\times',
  '\\setminus',
  '\\star',
  '\\cup',
  '\\cap',
  '\\ast',
  '\\sqcup',
  '\\sqcap',
  '\\circ',
  '\\vee',
  '\\lor',
  '\\wedge',
  '\\land',
  '\\bullet',
  '\\oplus',
  '\\ominus',
  '\\diamond',
  '\\odot',
  '\\oslash',
  '\\uplus',
  '\\otimes',
  '\\bigcirc',
  '\\amalg',
  '\\bigtriangleup',
  '\\bigtriangledown',
  '\\dagger',
  '\\lhd',
  '\\rhd',
  '\\ddagger',
  '\\unlhd',
  '\\unrhd',
  '\\wr',
  '\\sum',
  '\\bigcup',
  '\\bigvee',
  '\\prod',
  '\\bigcap',
  '\\bigwedge',
  '\\coprod',
  '\\bigsqcup',
  '\\biguplus',
  '\\int',
  '\\oint',
  '\\bigodot',
  '\\bigoplus',
  '\\bigotimes',
  '\\leftarrow',
  '\\gets',
  '\\longleftarrow',
  '\\rightarrow',
  '\\to',
  '\\longrightarrow',
  '\\leftrightarrow',
  '\\longleftrightarrow',
  '\\Leftarrow',
  '\\Longleftarrow',
  '\\Rightarrow',
  '\\Longrightarrow',
  '\\Leftrightarrow',
  '\\Longleftrightarrow',
  '\\mapsto',
  '\\longmapsto',
  '\\hookleftarrow',
  '\\hookrightarrow',
  '\\leftharpoonup',
  '\\rightharpoonup',
  '\\leftharpoondown',
  '\\rightharpoondown',
  '\\rightleftharpoons',
  '\\iff',
  '\\uparrow',
  '\\downarrow',
  '\\updownarrow',
  '\\Uparrow',
  '\\Downarrow',
  '\\Updownarrow',
  '\\nearrow',
  '\\searrow',
  '\\swarrow',
  '\\nwarrow',
  '\\leadsto',
  '\\uparrow',
  '\\lbrack',
  '\\rbrack',
  '\\downarrow',
  '\\lbrace',
  '\\{',
  '\\rbrace',
  '\\}',
  '\\updownarrow',
  '\\langle',
  '\\rangle',
  '\\Uparrow',
  '\\vert',
  '\\Vert',
  '\\|',
  '\\Downarrow',
  '\\backslash',
  '\\Updownarrow',
  '\\lfloor',
  '\\rfloor',
  '\\rceil',
  '\\lceil',
  '\\lgroup',
  '\\rgroup',
  '\\lmoustache',
  '\\rmoustache',
  '\\dots',
  '\\cdots',
  '\\vdots',
  '\\ddots',
  '\\hbar',
  '\\imath',
  '\\jmath',
  '\\ell',
  '\\Re',
  '\\Im',
  '\\aleph',
  '\\wp',
  '\\forall',
  '\\exists',
  '\\mho',
  '\\partial',
  "'",
  '\\prime',
  '\\emptyset',
  '\\infty',
  '\\nabla',
  '\\triangle',
  '\\Box',
  '\\Diamond',
  '\\bot',
  '\\top',
  '\\angle',
  '\\surd',
  '\\diamondsuit',
  '\\heartsuit',
  '\\clubsuit',
  '\\spadesuit',
  '\\neg',
  '\\lnot',
  '\\flat',
  '\\natural',
  '\\sharp',
  '\\dag',
  '\\ddag',
  '\\S',
  '\\P',
  '\\copyright',
  '\\pounds',
  '\\%',
  '\\ulcorner',
  '\\urcorner',
  '\\llcorner',
  '\\lrcorner',
  '\\lvert',
  '\\rvert',
  '\\lVert',
  '\\rVert',
  '\\digamma',
  '\\varkappa',
  '\\beth',
  '\\gimel',
  '\\daleth',
  '\\dotplus',
  '\\centerdot',
  '\\ltimes',
  '\\rtimes',
  '\\divideontimes',
  '\\doublecup',
  '\\doublecap',
  '\\smallsetminus',
  '\\veebar',
  '\\barwedge',
  '\\doublebarwedge',
  '\\boxplus',
  '\\boxminus',
  '\\circleddash',
  '\\boxtimes',
  '\\boxdot',
  '\\circledcirc',
  '\\intercal',
  '\\circledast',
  '\\rightthreetimes',
  '\\curlyvee',
  '\\curlywedge',
  '\\leftthreetimes',
  '\\lessdot',
  '\\gtrdot',
  '\\doteqdot',
  '\\leqslant',
  '\\geqslant',
  '\\risingdotseq',
  '\\eqslantless',
  '\\eqslantgtr',
  '\\fallingdotseq',
  '\\leqq',
  '\\geqq',
  '\\eqcirc',
  '\\lll',
  '\\llless',
  '\\ggg',
  '\\circeq',
  '\\lesssim',
  '\\gtrsim',
  '\\triangleq',
  '\\lessapprox',
  '\\gtrapprox',
  '\\bumpeq',
  '\\lessgtr',
  '\\gtrless',
  '\\Bumpeq',
  '\\lesseqgtr',
  '\\gtreqless',
  '\\thicksim',
  '\\lesseqqgtr',
  '\\gtreqqless',
  '\\thickapprox',
  '\\preccurlyeq',
  '\\succcurlyeq',
  '\\approxeq',
  '\\curlyeqprec',
  '\\curlyeqsucc',
  '\\backsim',
  '\\precsim',
  '\\succsim',
  '\\backsimeq',
  '\\precapprox',
  '\\succapprox',
  '\\vDash',
  '\\subseteqq',
  '\\supseteqq',
  '\\Vdash',
  '\\shortparallel',
  '\\Supset',
  '\\Vvdash',
  '\\blacktriangleleft',
  '\\sqsupset',
  '\\backepsilon',
  '\\vartriangleright',
  '\\because',
  '\\varpropto',
  '\\blacktriangleright',
  '\\Subset',
  '\\between',
  '\\trianglerighteq',
  '\\smallfrown',
  '\\pitchfork',
  '\\vartriangleleft',
  '\\shortmid',
  '\\smallsmile',
  '\\trianglelefteq',
  '\\therefore',
  '\\sqsubset',
]